### ISSUE TITLE
SocketCreateListener() failed

### ISSUE THREAD

**Issue by bluecow82** [EricJMarti/inventory-hunter#126]
First off, thank you Eric for creating this script giving us mere mortals a fighting chance. Even though I haven't been able to yet score a card, I have faith I will in time... once I get my errors worked out that is.

Aside from the Chromium issue detailed at #120 , I also get the following message  displayed when checking the docker logs:

```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
```

Not sure if the two issues are connected.
Thank you!

**Comment by xWildxChildx** [comment]
Would love some help on this too.

**Comment by EricJMarti** [comment]
Are you using Docker on Windows? If so, I think this is caused by incorrect line endings. Fixed in this commit: https://github.com/EricJMarti/inventory-hunter/commit/5adf144b8c35cd2c7958c4db4dedac528831a62d

**Comment by xWildxChildx** [comment]
> Are you using Docker on Windows? If so, I think this is caused by incorrect line endings. Fixed in this commit: [5adf144](https://github.com/EricJMarti/inventory-hunter/commit/5adf144b8c35cd2c7958c4db4dedac528831a62d)

I am unsure about the OP, but I am using docker on a Pi 3.

**Comment by bluecow82** [comment]
I’m on a Pi 4.

**Comment by xWildxChildx** [comment]
I wanted to follow up with an update in my situation, and include a disclaimer that I am very unfamiliar with programming of this sort. I don't even know the syntax we're talking about here (Python?) I got this Pi for my daughter, and was just desperate for a solution. - Side note, thank you Eric for offering this. Haven't scored a card yet, but I think this greatly improves my chances.

Moving on, I was learning a bit more about docker and came across a sort of "cleanup" command: 
$ docker system prune 
This cleaned up any resources not associated with a container (images, containers, volumes, networks). I suppose this solved the "x server already running" issue, but to be honest I'm not sure. I simply noticed I wasn't getting the error after running this command.

**Comment by krhubbard2** [comment]
> Moving on, I was learning a bit more about docker and came across a sort of "cleanup" command:
> $ docker system prune
> This cleaned up any resources not associated with a container (images, containers, volumes, networks). I suppose this solved the "x server already running" issue, but to be honest I'm not sure. I simply noticed I wasn't getting the error after running this command.

I'm also getting same error as OP. The prune command didn't fix it for me. It appears to still scrape appropriately some times.
At other times I also get a error:
`caught exception during request: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000`

This is on my Raspberry Pi 4 also.
